#!/bin/sh
set -eu

if [ ! -f /etc/ssh/keys/ssh_host_ed25519_key ]; then
    generate-hostkeys
fi
install -D -m 644 /e2e-keys/id_ed25519.pub /etc/ssh/authorized_keys/hamasen

exec supervise /usr/sbin/sshd -D -e
